# Generated by Django 5.0 on 2024-02-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0002_contactus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactus',
            table='Contactus',
        ),
    ]
